# [IMX219] pixel-size 1.12 um
image_width: 3280
image_height: 2464
camera_name: Waveshare_IMX219-160IR
camera_matrix:
  rows: 3
  cols: 3
  data: [
    3673.6,       0, 1640, 
         0, 2759.68, 1232, 
         0,       0,    1
  ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [
    1, 0, 0, 
    0, 1, 0, 
    0, 0, 1
  ]
projection_matrix:
  rows: 3
  cols: 4
  data: [
    3673.6,       0, 1640, 0,
         0, 2759.68, 1232, 0, 
         0,       0,    1, 0
  ]