# [IMX219-160IR] pixel-size 1.12 um
# [IMX219-160IR] focal-length 3.15 mm
image_width: 3280
image_height: 2464
camera_name: Waveshare_IMX219-160IR
camera_matrix:
  rows: 3
  cols: 3
  data: [
    2812.5,      0, 1640, 
         0, 2812.5, 1232, 
         0,      0,    1
  ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [
    1, 0, 0, 
    0, 1, 0, 
    0, 0, 1
  ]
projection_matrix:
  rows: 3
  cols: 4
  data: [
    2812.5,      0, 1640, 0,
         0, 2812.5, 1232, 0, 
         0,      0,    1, 0
  ]