teleop_robot:
  ros__parameters:
    require_enable_button: true

    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.4
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
