teleop_robot:
  ros__parameters:
    require_enable_button: true

    axis_linear:  # LS vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # LS horizontal
      yaw: 0
    scale_angular:
      yaw: 5.0
    scale_angular_turbo:
      yaw: 10.0

    enable_turbo_button: 4  # LB
    enable_button: 5        # RB
